export const OPTIONS = {
  scene_type: [
    { label: "ソロ（1人）",     value: "solo" },
    { label: "男女カップル",    value: "couple_mf" },
    { label: "女女カップル",    value: "couple_ff" },
    { label: "複数（3人以上）", value: "group" },
  ],
  gender: [
    { label: "女性", value: "female" },
    { label: "男性", value: "male" },
  ],
  age: [
    { label: "18-19歳",          value: "18 years old, young adult" },
    { label: "20代前半",          value: "early 20s, young woman" },
    { label: "20代前半（童顔）",  value: "early 20s, youthful face, babyface, young-looking" },
    { label: "20代後半",          value: "late 20s, mature young woman" },
    { label: "30代前半",          value: "early 30s, mature woman" },
    { label: "30代前半（童顔）",  value: "early 30s, youthful face, babyface" },
    { label: "30代後半",          value: "late 30s, mature woman" },
    { label: "40代",              value: "40 years old, milf" },
    { label: "熟女",              value: "mature woman, milf" },
  ],
  ethnicity: [
    { label: "日本人", value: "japanese" },
    { label: "韓国人", value: "korean" },
    { label: "中国人", value: "chinese" },
    { label: "白人",   value: "caucasian" },
    { label: "ラテン系", value: "latina" },
    { label: "黒人",   value: "black" },
  ],
  skin_tone: [
    { label: "色白",   value: "fair skin, pale skin" },
    { label: "標準",   value: "normal skin tone" },
    { label: "小麦色", value: "tan skin, lightly tanned" },
    { label: "褐色",   value: "dark skin, deeply tanned" },
  ],
  body_type: [
    { label: "ガリガリ",   value: "very thin, skinny, slender body, slim figure" },
    { label: "細身",       value: "slim, slender" },
    { label: "華奢",       value: "petite, slender" },
    { label: "標準",       value: "average build" },
    { label: "健康的",     value: "healthy body, fit" },
    { label: "グラマラス", value: "curvy, voluptuous" },
    { label: "豊満",       value: "chubby, plump" },
    { label: "ぽっちゃり", value: "chubby, soft body" },
    { label: "筋肉質",     value: "muscular, toned body, abs" },
    { label: "くびれ",     value: "narrow waist, hourglass figure" },
  ],
  breast_size: [
    { label: "ぺったんこ", value: "flat chest" },
    { label: "微乳",       value: "tiny breasts, small breasts" },
    { label: "小さめ",     value: "small breasts" },
    { label: "標準",       value: "medium breasts" },
    { label: "大きめ",     value: "large breasts" },
    { label: "巨乳",       value: "huge breasts" },
    { label: "爆乳",       value: "gigantic breasts, massive breasts" },
  ],
  pubic_hair: [
    { label: "未指定",         value: "" },
    { label: "無毛（パイパン）", value: "bald pussy, shaved" },
    { label: "ナチュラル",     value: "pubic hair" },
    { label: "薄め",           value: "thin pubic hair" },
    { label: "濃いめ",         value: "thick pubic hair" },
    { label: "整えた",         value: "trimmed pubic hair" },
    { label: "ハート型",       value: "heart-shaped pubic hair" },
  ],
  face_type: [
    { label: "美人",       value: "beautiful face, elegant face" },
    { label: "かわいい",   value: "cute face, lovely face" },
    { label: "ギャル",     value: "gyaru, tanned, makeup" },
    { label: "黒ギャル",   value: "kuro gyaru, dark skin, blonde hair" },
    { label: "クール",     value: "cool expression, sharp features" },
    { label: "知的",       value: "intelligent looking, refined face" },
    { label: "S系",        value: "dominant expression, sadistic smile" },
    { label: "M系",        value: "submissive face, meek expression" },
    { label: "メスガキ",   value: "cocky face, smug face, teasing smile" },
    { label: "ヤンデレ",   value: "yandere, obsessive expression, crazy eyes" },
    { label: "明るい",     value: "cheerful face, bright smile" },
    { label: "セクシー",   value: "sexy face, seductive expression" },
    { label: "童顔",       value: "babyface, youthful face" },
    { label: "大人っぽい", value: "mature face, grown-up features" },
    { label: "清楚",       value: "pure looking, innocent face" },
    { label: "妖艶",       value: "bewitching face, sultry" },
    { label: "凛々しい",   value: "dignified face, noble features" },
    { label: "エキゾチック", value: "exotic face, foreign features" },
  ],
  hair_color: [
    { label: "黒",   value: "black hair" },
    { label: "茶",   value: "brown hair" },
    { label: "金",   value: "blonde hair" },
    { label: "白",   value: "white hair" },
    { label: "銀",   value: "silver hair" },
    { label: "赤",   value: "red hair" },
    { label: "ピンク", value: "pink hair" },
  ],
  hair_style: [
    { label: "ベリーショート",   value: "very short hair" },
    { label: "ショート",         value: "short hair" },
    { label: "ショートボブ",     value: "short bob" },
    { label: "ボブ",             value: "bob cut" },
    { label: "ミディアム",       value: "medium hair" },
    { label: "セミロング",       value: "medium long hair" },
    { label: "ロング",           value: "long hair" },
    { label: "超ロング",         value: "very long hair, waist-length hair" },
    { label: "ストレート",       value: "straight hair" },
    { label: "ウェーブ",         value: "wavy hair" },
    { label: "カール",           value: "curly hair" },
    { label: "巻き髪",           value: "drill hair, ringlets" },
    { label: "パーマ",           value: "permed hair" },
    { label: "ポニーテール",     value: "ponytail" },
    { label: "ハイポニー",       value: "high ponytail" },
    { label: "サイドポニー",     value: "side ponytail" },
    { label: "ツインテール",     value: "twintails" },
    { label: "低めツインテ",     value: "low twintails" },
    { label: "お団子",           value: "hair bun" },
    { label: "ダブルお団子",     value: "double bun" },
    { label: "三つ編み",         value: "braid" },
    { label: "ツイン三つ編み",   value: "twin braids" },
    { label: "ハーフアップ",     value: "half updo" },
    { label: "ぱっつん",         value: "blunt bangs" },
    { label: "流し前髪",         value: "swept bangs" },
    { label: "センター分け",     value: "parted bangs" },
    { label: "姫カット",         value: "hime cut" },
    { label: "アシメ",           value: "asymmetric bangs" },
  ],
  eye_color: [
    { label: "茶", value: "brown eyes" },
    { label: "黒", value: "black eyes" },
    { label: "青", value: "blue eyes" },
    { label: "緑", value: "green eyes" },
    { label: "赤", value: "red eyes" },
    { label: "紫", value: "purple eyes" },
    { label: "金", value: "golden eyes" },
  ],
  eye_shape: [
    { label: "標準",     value: "normal eyes" },
    { label: "大きい",   value: "big eyes" },
    { label: "切れ長",   value: "narrow eyes, slanted eyes" },
    { label: "たれ目",   value: "drooping eyes" },
    { label: "つり目",   value: "tsurime, slanted eyes" },
    { label: "三白眼",   value: "sanpaku, three white eyes" },
    { label: "ジト目",   value: "half-closed eyes, dull eyes" },
    { label: "半目",     value: "half-closed eyes" },
    { label: "閉じる",   value: "closed eyes" },
    { label: "片目閉じ", value: "one eye closed, wink" },
    { label: "ハートの瞳", value: "heart-shaped pupils, heart eyes" },
    { label: "星の瞳",   value: "star-shaped pupils" },
    { label: "虚ろ",     value: "empty eyes, blank eyes" },
    { label: "焦点合わず", value: "unfocused eyes, dazed eyes" },
    { label: "とろん目", value: "glassy eyes, hazy eyes" },
    { label: "白目",     value: "rolling eyes, rolled eyes" },
    { label: "涙目",     value: "tearful, teary eyes" },
    { label: "上目遣い", value: "looking up, upturned eyes" },
    { label: "流し目",   value: "looking to the side, sidelong glance" },
  ],
  mouth: [
    { label: "普通",     value: "normal mouth" },
    { label: "微笑",     value: "slight smile" },
    { label: "笑顔",     value: "smile" },
    { label: "大笑い",   value: "laughing, open mouth smile" },
    { label: "半開き",   value: "parted lips" },
    { label: "大きく開く", value: "open mouth" },
    { label: "舌出し",   value: "tongue out" },
    { label: "唇舐め",   value: "licking lips" },
    { label: "唾液",     value: "saliva, drooling" },
    { label: "涎",       value: "drooling, saliva trail" },
    { label: "キス顔",   value: "face waiting for kiss, puckered lips" },
    { label: "噛みしめ", value: "clenching jaw, biting" },
    { label: "唇噛み",   value: "biting lip" },
    { label: "口に手",   value: "hand over mouth" },
    { label: "口に物",   value: "mouth hold, holding object in mouth" },
    { label: "口枷",     value: "gag, gagged" },
    { label: "ふぇら口", value: "fellatio gesture, sucking" },
  ],
  expression: [
    { label: "無表情",   value: "expressionless" },
    { label: "笑顔",     value: "smiling" },
    { label: "困り顔",   value: "troubled face" },
    { label: "怒り",     value: "angry, frowning" },
    { label: "悲しい",   value: "sad, sorrowful" },
    { label: "驚き",     value: "surprised" },
    { label: "真剣",     value: "serious face" },
    { label: "恥じらい", value: "embarrassed, blushing" },
    { label: "赤面",     value: "blushing, full-face blush" },
    { label: "誘惑",     value: "seductive expression" },
    { label: "興奮",     value: "aroused, horny expression" },
    { label: "快感",     value: "pleasure, pleasured face" },
    { label: "トロ顔",   value: "glassy eyes, saliva, open mouth" },
    { label: "アヘ顔",   value: "ahegao" },
    { label: "放心",     value: "empty eyes, saliva, open mouth" },
    { label: "気絶",     value: "blank eyes, saliva, open mouth" },
    { label: "我慢顔",   value: "close eyes tightly, clenching jaw, tearful" },
    { label: "悶絶顔",   value: "rolling eyes, tearful, clenching jaw, saliva" },
    { label: "身悶え",   value: "rolling eyes, saliva, open mouth" },
    { label: "涙",       value: "crying, tears" },
    { label: "嗚咽",     value: "sobbing, tears streaming" },
    { label: "屈辱",     value: "humiliated, ashamed" },
    { label: "恍惚",     value: "ecstatic, blissful expression" },
    { label: "物欲しげ", value: "wanting, lustful expression" },
  ],
  outfit: [
    { label: "なし",               value: "" },
    { label: "制服",               value: "school uniform" },
    { label: "セーラー服",         value: "sailor uniform" },
    { label: "ブラウス",           value: "blouse, formal shirt" },
    { label: "Tシャツ",            value: "t-shirt, casual wear" },
    { label: "ワンピース",         value: "dress, one-piece dress" },
    { label: "ニット",             value: "knit sweater" },
    { label: "オフィス",           value: "business suit, office wear" },
    { label: "ドレス",             value: "elegant dress, evening gown" },
    { label: "着物",               value: "kimono" },
    { label: "浴衣",               value: "yukata" },
    { label: "水着",               value: "swimsuit, bikini" },
    { label: "ビキニ",             value: "string bikini, micro bikini" },
    { label: "競泳水着",           value: "competitive swimsuit, one-piece swimsuit" },
    { label: "スクール水着",       value: "school swimsuit" },
    { label: "ランジェリー",       value: "lingerie, underwear" },
    { label: "セクシーランジェリー", value: "sexy lingerie, see-through lingerie" },
    { label: "ベビードール",       value: "babydoll lingerie, sheer babydoll" },
    { label: "Tバック",            value: "thong, g-string" },
    { label: "ガーターベルト",     value: "garter belt, stockings" },
    { label: "網タイツ",           value: "fishnet stockings" },
    { label: "スポーツ",           value: "sportswear, athletic wear" },
    { label: "メイド服",           value: "maid outfit" },
    { label: "ナース服",           value: "nurse uniform" },
    { label: "バニーガール",       value: "bunny girl outfit, bunny suit" },
    { label: "チャイナドレス",     value: "china dress, qipao" },
    { label: "シャツのみ",         value: "wearing only an oversized shirt, boyfriend shirt" },
    { label: "バスタオル",         value: "wrapped in bath towel, towel only" },
  ],
  outfit_color: [
    { label: "白",   value: "white" },
    { label: "黒",   value: "black" },
    { label: "赤",   value: "red" },
    { label: "青",   value: "blue" },
    { label: "ピンク", value: "pink" },
    { label: "紫",   value: "purple" },
    { label: "黄",   value: "yellow" },
    { label: "緑",   value: "green" },
    { label: "ベージュ", value: "beige" },
  ],
  outfit_material: [
    { label: "標準",     value: "" },
    { label: "レース",   value: "lace" },
    { label: "シルク",   value: "silk, satin" },
    { label: "メッシュ", value: "mesh" },
    { label: "ラテックス", value: "latex" },
    { label: "レザー",   value: "leather" },
    { label: "シースルー", value: "sheer fabric, transparent" },
    { label: "デニム",   value: "denim" },
    { label: "ニット",   value: "knit" },
  ],
  outfit_state: [
    { label: "濡れ",         value: "wet clothes, soaked" },
    { label: "はだけた",     value: "open shirt, partially undressed" },
    { label: "ずり下ろした", value: "pulled down, slipping off shoulder" },
    { label: "めくれた",     value: "lifted skirt, skirt flip" },
    { label: "破れた",       value: "torn clothes, ripped" },
    { label: "汗ばんだ",     value: "sweaty, glistening skin" },
  ],
  underwear: [
    { label: "ノーマルブラ",   value: "bra" },
    { label: "スポーツブラ",   value: "sports bra" },
    { label: "レースブラ",     value: "lace bra" },
    { label: "ブラレス",       value: "no bra" },
    { label: "ノーマルパンティ", value: "panties" },
    { label: "Tバック",        value: "thong" },
    { label: "レースパンティ", value: "lace panties" },
    { label: "紐パン",         value: "side-tie panties" },
    { label: "ノーパン",       value: "no panties" },
    { label: "ガーターベルト", value: "garter belt" },
    { label: "ストッキング",   value: "stockings, thighhighs" },
    { label: "ニーソックス",   value: "kneehighs" },
    { label: "ベビードール",   value: "babydoll, lingerie" },
    { label: "コルセット",     value: "corset" },
    { label: "Cストラップ",    value: "c-string" },
    { label: "パンツ丸見え",   value: "panty shot, panties visible" },
  ],
  exposure: [
    { label: "保守的",   value: "modest clothing, fully covered" },
    { label: "標準",     value: "" },
    { label: "やや露出", value: "slightly revealing outfit" },
    { label: "露出多め", value: "revealing outfit, exposed skin" },
    { label: "セクシー", value: "very revealing, sexy outfit" },
  ],
  shot_type: [
    { label: "全身",       value: "full body" },
    { label: "上半身",     value: "upper body" },
    { label: "顔アップ",   value: "close-up, face focus" },
    { label: "バストアップ", value: "bust shot" },
    { label: "カウボーイ", value: "cowboy shot" },
    { label: "ポートレート", value: "portrait" },
    { label: "局部アップ", value: "pussy focus" },
    { label: "胸アップ",   value: "breast focus" },
  ],
  angle: [
    { label: "正面",       value: "front" },
    { label: "横",         value: "side" },
    { label: "斜め",       value: "3/4" },
    { label: "煽り",       value: "from below" },
    { label: "俯瞰",       value: "from above" },
    { label: "真上",       value: "from directly above, top-down view" },
    { label: "真下",       value: "from directly below, worm's-eye view" },
    { label: "ローアングル", value: "low angle shot" },
    { label: "ハイアングル", value: "high angle shot" },
    { label: "POV",        value: "POV, first person view" },
    { label: "肩越し",     value: "over the shoulder" },
    { label: "自撮り風",   value: "selfie" },
    { label: "鏡越し",     value: "mirror selfie" },
    { label: "覗き見",     value: "peeking" },
    { label: "アイレベル", value: "eye level" },
  ],
  pose: [
    { label: "立ちポーズ",   value: "standing" },
    { label: "座り",         value: "sitting" },
    { label: "正座",         value: "seiza" },
    { label: "あぐら",       value: "indian style" },
    { label: "横座り",       value: "wariza" },
    { label: "仰向け",       value: "on back" },
    { label: "うつ伏せ",     value: "on stomach" },
    { label: "横向き",       value: "on side" },
    { label: "四つん這い",   value: "all fours" },
    { label: "しゃがみ",     value: "squatting" },
    { label: "ひざまずき",   value: "kneeling" },
    { label: "反り返り",     value: "arched back" },
    { label: "手を後ろ",     value: "arms behind back" },
    { label: "手を頭",       value: "arms up, hands on head" },
    { label: "胸を強調",     value: "pushing breasts together" },
    { label: "お尻突き出し", value: "presenting ass" },
    { label: "開脚",         value: "spread legs" },
    { label: "M字開脚",      value: "m legs" },
    { label: "膝立て",       value: "knees up" },
    { label: "自慰",         value: "masturbation" },
    { label: "誘惑",         value: "seductive pose" },
    { label: "恥じらい",     value: "embarrassed pose, covering" },
    { label: "見せつけ",     value: "showing off" },
  ],
  position: [
    { label: "正常位",     value: "missionary" },
    { label: "騎乗位",     value: "cowgirl position" },
    { label: "背面騎乗位", value: "reverse cowgirl" },
    { label: "後背位",     value: "doggystyle" },
    { label: "対面座位",   value: "sitting sex" },
    { label: "立位",       value: "standing sex" },
    { label: "横位",       value: "spooning" },
    { label: "寝バック",   value: "prone bone" },
    { label: "抱擁",       value: "embracing" },
    { label: "添い寝",     value: "lying together" },
    { label: "重なり",     value: "on top of another" },
    { label: "対面",       value: "face to face" },
    { label: "跨り",       value: "straddling" },
    { label: "シックスナイン", value: "69" },
    { label: "囲み",       value: "surrounded" },
    { label: "並列",       value: "side by side" },
    { label: "重なり多人数", value: "pile" },
  ],
  action: [
    { label: "キス",       value: "kissing" },
    { label: "ディープキス", value: "french kiss, tongue" },
    { label: "抱擁",       value: "hugging" },
    { label: "愛撫",       value: "caressing, fondling" },
    { label: "胸を揉む",   value: "breast grab" },
    { label: "髪を撫でる", value: "hair touching" },
    { label: "行為中",     value: "sex" },
    { label: "激しい行為", value: "rough sex" },
    { label: "ソフトな行為", value: "gentle sex" },
    { label: "フェラチオ", value: "fellatio" },
    { label: "クンニ",     value: "cunnilingus" },
    { label: "手コキ",     value: "handjob" },
    { label: "パイズリ",   value: "paizuri" },
    { label: "絶頂中",     value: "orgasm, ahegao" },
    { label: "行為後",     value: "after sex, afterglow" },
    { label: "中出し",     value: "cum inside" },
    { label: "ぶっかけ",   value: "cum on body, bukkake" },
  ],
  location: [
    { label: "寝室",   value: "bedroom" },
    { label: "バスルーム", value: "bathroom" },
    { label: "シャワー室", value: "shower" },
    { label: "リビング", value: "living room" },
    { label: "キッチン", value: "kitchen" },
    { label: "教室",   value: "classroom" },
    { label: "保健室", value: "nurse office" },
    { label: "オフィス", value: "office" },
    { label: "会議室", value: "meeting room" },
    { label: "ホテル", value: "hotel room" },
    { label: "ラブホ", value: "love hotel" },
    { label: "温泉",   value: "hot spring, onsen" },
    { label: "プール", value: "pool" },
    { label: "ビーチ", value: "beach" },
    { label: "海",     value: "ocean" },
    { label: "公園",   value: "park" },
    { label: "神社",   value: "shrine" },
    { label: "路地",   value: "alley" },
    { label: "電車内", value: "train interior" },
    { label: "車内",   value: "car interior" },
    { label: "屋上",   value: "rooftop" },
    { label: "森",     value: "forest" },
    { label: "廃墟",   value: "ruins" },
  ],
  situation: [
    { label: "通常",   value: "" },
    { label: "起床",   value: "just woke up, morning" },
    { label: "入浴中", value: "bathing" },
    { label: "入浴後", value: "wet hair, after bath" },
    { label: "着替え中", value: "changing clothes, undressing" },
    { label: "着替え後", value: "getting dressed" },
    { label: "食事中", value: "eating" },
    { label: "仕事中", value: "working" },
    { label: "休憩中", value: "resting, on break" },
    { label: "寝起き", value: "lazy morning" },
    { label: "就寝前", value: "before sleep" },
    { label: "居眠り", value: "sleeping, dozing" },
    { label: "拘束",   value: "bondage, tied up" },
    { label: "監禁",   value: "confined, captive" },
    { label: "公衆",   value: "in public" },
    { label: "屋外露出", value: "exhibitionism, outdoor" },
    { label: "痴漢",   value: "groping" },
    { label: "覗き",   value: "voyeurism" },
    { label: "隠れて", value: "hiding, secret" },
    { label: "待機",   value: "waiting" },
    { label: "誘惑中", value: "seducing" },
  ],
  mood: [
    { label: "甘い",       value: "sweet, romantic" },
    { label: "激しい",     value: "passionate, intense" },
    { label: "淫靡",       value: "lewd, erotic" },
    { label: "神聖",       value: "pure, divine" },
    { label: "背徳的",     value: "forbidden, immoral" },
    { label: "切ない",     value: "melancholic" },
    { label: "ミステリアス", value: "mysterious" },
    { label: "退廃的",     value: "decadent" },
    { label: "緊張感",     value: "tense atmosphere" },
    { label: "リラックス", value: "relaxed, calm" },
    { label: "怪しい",     value: "suspicious, eerie" },
    { label: "夜の雰囲気", value: "night atmosphere" },
  ],
  nsfw_level: [
    { label: "なし",          value: "" },
    { label: "軽（チラ見せ）", value: "cleavage, suggestive, slightly revealing" },
    { label: "中（下着）",    value: "lingerie, underwear, panties" },
    { label: "強（トップレス）", value: "topless, exposed breasts" },
    { label: "全裸",          value: "nude, naked, completely bare" },
  ],
} as const;

export type ModelFamily = "sdxl_real" | "pony_real" | "illustrious_anime";

export interface ModelDef {
  label: string;
  value: string;
  family: ModelFamily;
  description: string;
  basePrompt: string;
  baseNegative: string;
  recommended: {
    cfg_scale: number;
    steps: number;
    sampler: string;
    width: number;
    height: number;
  };
}

export const MODELS: ModelDef[] = [
  {
    label: "Nova Asian XL v7.0",
    value: "novaAsianXL_illustrious_v7.safetensors",
    family: "illustrious_anime",
    description: "アジア系リアル・Illustrious系",
    basePrompt: "masterpiece, best quality, amazing quality, very aesthetic, high resolution, ultra-detailed, absurdres, scenery, photorealistic, depth of field, photorealistic details",
    baseNegative: "anime, 3d, rendered, modern, old, oldest, cartoon, graphic, text, painting, crayon, graphite, abstract, glitch, deformed, mutated, ugly, disfigured, long body, lowres, bad anatomy, bad hands, missing fingers, extra digits, fewer digits, cropped, very displeasing, worst quality, bad quality, sketch, jpeg artifacts, signature, watermark, username, simple background",
    recommended: {
      cfg_scale: 4.0,
      steps: 30,
      sampler: "Euler a",
      width: 832,
      height: 1216,
    },
  },
  {
    label: "Hassaku XL (アニメ)",
    value: "hassakuXLIllustrious_v22.safetensors",
    family: "illustrious_anime",
    description: "アニメ系・Illustrious系・Danbooruタグ推奨",
    basePrompt: "masterpiece, best quality, very aware, newest, absurdres, ultra-detailed, detailed face, detailed eyes",
    baseNegative: "worst quality, bad quality, jpeg artifacts, source_pony, source_furry, signature, watermark, monochrome, sketch, lowres, bad anatomy, bad hands, missing fingers, extra fingers",
    recommended: {
      cfg_scale: 5.0,
      steps: 28,
      sampler: "Euler a",
      width: 832,
      height: 1216,
    },
  },
];
