export const OPTIONS = {
  gender: [
    { label: "女性", value: "female" },
    { label: "男性", value: "male" },
  ],
  age: [
    { label: "ティーン", value: "teen" },
    { label: "20代前半", value: "young adult, early 20s" },
    { label: "20代後半", value: "adult, late 20s" },
    { label: "30代", value: "mature, 30s" },
    { label: "熟女", value: "mature woman, milf" },
  ],
  ethnicity: [
    { label: "日本人", value: "japanese" },
    { label: "韓国人", value: "korean" },
    { label: "中国人", value: "chinese" },
    { label: "白人", value: "caucasian" },
    { label: "ラテン系", value: "latina" },
    { label: "黒人", value: "black" },
  ],
  skin_tone: [
    { label: "色白", value: "fair skin, pale skin" },
    { label: "標準", value: "normal skin tone" },
    { label: "小麦色", value: "tan skin, lightly tanned" },
    { label: "褐色", value: "dark skin, deeply tanned" },
  ],
  body_type: [
    { label: "華奢", value: "very slender, petite, thin body" },
    { label: "スレンダー", value: "slender, lean body" },
    { label: "スリム", value: "slim" },
    { label: "普通", value: "normal body" },
    { label: "グラマー", value: "curvy" },
    { label: "むっちり", value: "chubby, voluptuous" },
  ],
  breast_size: [
    { label: "小さい", value: "small breasts" },
    { label: "普通", value: "medium breasts" },
    { label: "大きい", value: "large breasts, busty" },
    { label: "爆乳", value: "huge breasts, very large breasts" },
  ],
  face_type: [
    { label: "清楚", value: "elegant beauty, refined face, pure look" },
    { label: "ギャル", value: "gyaru style, glamorous makeup, bold look" },
    { label: "クール", value: "cool beauty, sharp features, mature look" },
    { label: "元気", value: "cheerful face, bright expression, lively look" },
    { label: "上品", value: "graceful, sophisticated face, classy" },
    { label: "アンニュイ", value: "languid expression, dreamy look, melancholic beauty" },
    { label: "セクシー", value: "sexy face, sensual look, sultry beauty" },
    { label: "童顔", value: "baby face, youthful features, cute face" },
  ],
  hair_color: [
    { label: "黒", value: "black hair" },
    { label: "茶", value: "brown hair" },
    { label: "金", value: "blonde hair" },
    { label: "白", value: "white hair" },
    { label: "銀", value: "silver hair" },
    { label: "赤", value: "red hair" },
    { label: "ピンク", value: "pink hair" },
  ],
  hair_style: [
    { label: "ショート", value: "short hair" },
    { label: "ボブ", value: "bob hair" },
    { label: "セミロング", value: "medium hair" },
    { label: "ロング", value: "long hair" },
    { label: "ツインテール", value: "twin tails" },
    { label: "ポニーテール", value: "ponytail" },
    { label: "お団子", value: "hair bun" },
    { label: "巻き髪", value: "curly hair, wavy hair" },
  ],
  eye_color: [
    { label: "茶", value: "brown eyes" },
    { label: "黒", value: "black eyes" },
    { label: "青", value: "blue eyes" },
    { label: "緑", value: "green eyes" },
    { label: "赤", value: "red eyes" },
    { label: "紫", value: "purple eyes" },
    { label: "金", value: "golden eyes" },
  ],
  eye_shape: [
    { label: "大きい", value: "big eyes" },
    { label: "切れ長", value: "sharp eyes, slanted eyes" },
    { label: "垂れ目", value: "droopy eyes" },
    { label: "つり目", value: "tsurime, upturned eyes" },
  ],
  mouth: [
    { label: "微笑み", value: "smile mouth" },
    { label: "自然", value: "neutral mouth" },
    { label: "開口", value: "open mouth" },
    { label: "舌出し", value: "tongue out" },
  ],
  expression: [
    { label: "笑顔", value: "happy expression, bright smile" },
    { label: "微笑み", value: "soft smile, gentle smile" },
    { label: "真顔", value: "neutral expression" },
    { label: "色っぽい", value: "seductive expression, sultry look" },
    { label: "挑発的", value: "provocative expression, teasing look" },
    { label: "恥ずかしげ", value: "shy expression, blushing" },
    { label: "切ない", value: "melancholic expression, longing look" },
    { label: "驚き", value: "surprised expression" },
    { label: "ウィンク", value: "winking, one eye closed" },
    { label: "誘惑", value: "seductive expression, bedroom eyes, sultry look" },
    { label: "恍惚", value: "ecstatic expression, blissful look" },
    { label: "焦らし", value: "teasing expression, playful smirk" },
    { label: "上目遣い", value: "looking up at viewer, upward gaze" },
    { label: "見下し", value: "looking down at viewer, condescending look" },
    { label: "潤んだ瞳", value: "teary eyes, watery eyes" },
    { label: "頬染め", value: "blushing cheeks, flushed face" },
    { label: "舌なめずり", value: "licking lips, tongue out" },
    { label: "口元に手", value: "hand near mouth, covering mouth" },
  ],
  outfit: [
    { label: "なし", value: "" },
    { label: "制服", value: "school uniform" },
    { label: "セーラー服", value: "sailor uniform" },
    { label: "ブラウス", value: "blouse, formal shirt" },
    { label: "Tシャツ", value: "t-shirt, casual wear" },
    { label: "ワンピース", value: "dress, one-piece dress" },
    { label: "ニット", value: "knit sweater" },
    { label: "オフィス", value: "business suit, office wear" },
    { label: "ドレス", value: "elegant dress, evening gown" },
    { label: "着物", value: "kimono" },
    { label: "浴衣", value: "yukata" },
    { label: "水着", value: "swimsuit, bikini" },
    { label: "ビキニ", value: "string bikini, micro bikini" },
    { label: "競泳水着", value: "competitive swimsuit, one-piece swimsuit" },
    { label: "スクール水着", value: "school swimsuit" },
    { label: "ランジェリー", value: "lingerie, underwear" },
    { label: "セクシーランジェリー", value: "sexy lingerie, see-through lingerie" },
    { label: "ベビードール", value: "babydoll lingerie, sheer babydoll" },
    { label: "Tバック", value: "thong, g-string" },
    { label: "ガーターベルト", value: "garter belt, stockings" },
    { label: "網タイツ", value: "fishnet stockings" },
    { label: "スポーツ", value: "sportswear, athletic wear" },
    { label: "メイド服", value: "maid outfit" },
    { label: "ナース服", value: "nurse uniform" },
    { label: "バニーガール", value: "bunny girl outfit, bunny suit" },
    { label: "チャイナドレス", value: "china dress, qipao" },
    { label: "シャツのみ", value: "wearing only an oversized shirt, boyfriend shirt" },
    { label: "バスタオル", value: "wrapped in bath towel, towel only" },
  ],
  outfit_color: [
    { label: "白", value: "white" },
    { label: "黒", value: "black" },
    { label: "赤", value: "red" },
    { label: "青", value: "blue" },
    { label: "ピンク", value: "pink" },
    { label: "紫", value: "purple" },
    { label: "黄", value: "yellow" },
    { label: "緑", value: "green" },
    { label: "ベージュ", value: "beige" },
  ],
  outfit_material: [
    { label: "標準", value: "" },
    { label: "レース", value: "lace" },
    { label: "シルク", value: "silk, satin" },
    { label: "メッシュ", value: "mesh" },
    { label: "ラテックス", value: "latex" },
    { label: "レザー", value: "leather" },
    { label: "シースルー", value: "sheer fabric, transparent" },
    { label: "デニム", value: "denim" },
    { label: "ニット", value: "knit" },
  ],
  outfit_state: [
    { label: "標準", value: "" },
    { label: "濡れ", value: "wet clothes, soaked" },
    { label: "はだけた", value: "open shirt, partially undressed" },
    { label: "ずり下ろした", value: "pulled down, slipping off shoulder" },
    { label: "めくれた", value: "lifted skirt, skirt flip" },
    { label: "破れた", value: "torn clothes, ripped" },
    { label: "汗ばんだ", value: "sweaty, glistening skin" },
  ],
  exposure: [
    { label: "保守的", value: "modest clothing, fully covered" },
    { label: "標準", value: "" },
    { label: "やや露出", value: "slightly revealing outfit" },
    { label: "露出多め", value: "revealing outfit, exposed skin" },
    { label: "セクシー", value: "very revealing, sexy outfit" },
  ],
  composition: [
    { label: "全身", value: "full body" },
    { label: "上半身", value: "upper body" },
    { label: "カウボーイ", value: "cowboy shot" },
    { label: "クローズアップ", value: "close-up" },
    { label: "ポートレート", value: "portrait, head and shoulders" },
    { label: "腰から上", value: "waist up shot" },
    { label: "膝まで", value: "knee shot, mid-thigh up" },
    { label: "足元から", value: "low angle full body shot" },
    { label: "顔アップ", value: "face close-up" },
    { label: "目のアップ", value: "extreme close-up of eyes" },
  ],
  angle: [
    { label: "正面", value: "front" },
    { label: "横", value: "side" },
    { label: "斜め", value: "3/4" },
    { label: "煽り", value: "from below" },
    { label: "俯瞰", value: "from above" },
    { label: "真上", value: "from directly above, top-down view" },
    { label: "真下", value: "from directly below, worm's-eye view" },
    { label: "ローアングル", value: "low angle shot" },
    { label: "ハイアングル", value: "high angle shot" },
    { label: "POV", value: "POV, first person view" },
    { label: "肩越し", value: "over the shoulder" },
  ],
  pose: [
    { label: "立ち", value: "standing" },
    { label: "座り", value: "sitting" },
    { label: "横たわる", value: "lying down" },
    { label: "ひざまずく", value: "kneeling" },
    { label: "腕組み", value: "arms crossed" },
    { label: "腰に手", value: "hand on hip" },
    { label: "腕を上げる", value: "arms raised" },
    { label: "振り返り", value: "looking back" },
    { label: "足を広げる", value: "spread legs, standing with legs apart" },
    { label: "背中を反らす", value: "arching the back" },
    { label: "谷間強調", value: "showcasing cleavage, leaning forward" },
    { label: "お尻強調", value: "booty pose, looking back over shoulder" },
    { label: "椅子にまたがる", value: "straddling a chair" },
    { label: "誘惑的", value: "seductive pose, sultry stance" },
    { label: "四つん這い", value: "on all fours, kneeling on hands and knees" },
    { label: "うつ伏せ", value: "lying on stomach, prone position" },
    { label: "あおむけ", value: "lying on back, supine position" },
    { label: "横向きで寝る", value: "lying on side" },
    { label: "膝立ち", value: "kneeling, on knees" },
    { label: "片膝立ち", value: "one knee up, asymmetric kneeling" },
    { label: "M字開脚", value: "spread legs wide, M-shaped legs" },
    { label: "壁にもたれる", value: "leaning against wall" },
    { label: "壁ドン", value: "pinned against wall" },
    { label: "胸を強調", value: "pushing breasts together, emphasizing breasts" },
    { label: "服をたくし上げる", value: "lifting shirt, holding clothes up" },
    { label: "シャツの裾をくわえる", value: "biting clothes, mouth holding fabric" },
    { label: "腰をくねらせる", value: "swaying hips, hip sway" },
    { label: "後ろ手に縛る", value: "hands behind back" },
    { label: "髪をかきあげる", value: "running hand through hair" },
  ],
  camera: [
    { label: "標準", value: "" },
    { label: "DSLR", value: "shot on Canon EOS 5D, DSLR photography" },
    { label: "ライカ", value: "shot on Leica T, leica photography" },
    { label: "ポラロイド", value: "shot on Polaroid SX-70, polaroid photo" },
    { label: "アナログ", value: "analog photo, film grain, 35mm film" },
    { label: "グラビア", value: "glamour photography, magazine cover" },
    { label: "アマチュア", value: "amateur photo, candid photo, snapshot" },
    { label: "RAW", value: "RAW photo, unprocessed" },
  ],
  lighting: [
    { label: "標準", value: "" },
    { label: "シネマ", value: "cinematic lighting, dramatic atmosphere" },
    { label: "ソフト", value: "soft lighting, diffused light" },
    { label: "ドラマチック", value: "dramatic lighting, high contrast" },
    { label: "ローキー", value: "low key lighting, moody atmosphere" },
    { label: "ゴールデンアワー", value: "warm golden hour lighting, sunset glow" },
    { label: "フラッシュ", value: "bright flash photography, direct flash" },
    { label: "ネオン", value: "neon lighting, colorful neon glow" },
    { label: "逆光", value: "backlit, rim lighting" },
    { label: "窓辺の自然光", value: "natural window light, morning light" },
  ],
  nsfw_level: [
    { label: "なし", value: "" },
    { label: "軽（チラ見せ）", value: "cleavage, suggestive, slightly revealing" },
    { label: "中（下着）", value: "lingerie, underwear, panties" },
    { label: "強（トップレス）", value: "topless, exposed breasts" },
    { label: "全裸", value: "nude, naked, completely bare" },
  ],
  nsfw_situation: [
    { label: "なし", value: "" },
    { label: "バスルーム", value: "in the bathroom, shower scene" },
    { label: "ベッド", value: "in bed, on the bed" },
    { label: "温泉", value: "hot springs, onsen" },
    { label: "更衣室", value: "in the changing room, locker room" },
    { label: "サウナ", value: "in the sauna" },
    { label: "プール", value: "by the pool, poolside" },
    { label: "教室で1人", value: "alone in classroom, after school" },
    { label: "オフィスで1人", value: "alone in office, late at work" },
  ],
  background: [
    { label: "白背景", value: "white background, simple background" },
    { label: "街並み", value: "city street" },
    { label: "夜の都市", value: "night city, neon lights" },
    { label: "和室", value: "japanese room, tatami" },
    { label: "幻想の森", value: "fantasy forest" },
    { label: "ビーチ", value: "beach, ocean" },
    { label: "ベッドルーム", value: "bedroom interior" },
    { label: "バスルーム", value: "bathroom" },
    { label: "オフィス", value: "office interior" },
    { label: "教室", value: "classroom" },
    { label: "公園", value: "park, outdoor" },
    { label: "カフェ", value: "cafe interior" },
    { label: "ホテルの部屋", value: "luxury hotel room, hotel suite" },
    { label: "車内", value: "inside a car, car interior" },
    { label: "更衣室", value: "changing room, locker room" },
    { label: "温泉", value: "japanese hot springs, onsen" },
    { label: "雪景色", value: "snowy landscape, winter scene" },
    { label: "桜の下", value: "under cherry blossoms, sakura" },
    { label: "夕焼け", value: "sunset, golden hour" },
    { label: "屋上", value: "rooftop, building rooftop" },
    { label: "プール", value: "swimming pool, poolside" },
    { label: "高級レストラン", value: "fancy restaurant interior" },
    { label: "ライブハウス", value: "concert venue, neon stage" },
  ],
} as const;

export type ModelFamily = "sdxl_real" | "pony_real" | "illustrious_anime";

export interface ModelDef {
  label: string;
  value: string;
  family: ModelFamily;
  description: string;
  basePrompt: string;
  baseNegative: string;
  recommended: {
    cfg_scale: number;
    steps: number;
    sampler: string;
    width: number;
    height: number;
  };
}

export const MODELS: ModelDef[] = [
  {
    label: "Nova Asian XL v7.0",
    value: "novaAsianXL_illustrious_v7.safetensors",
    family: "illustrious_anime",
    description: "アジア系リアル・Illustrious系",
    basePrompt: "masterpiece, best quality, amazing quality, very aesthetic, high resolution, ultra-detailed, absurdres, scenery, photorealistic, depth of field, photorealistic details",
    baseNegative: "anime, 3d, rendered, modern, old, oldest, cartoon, graphic, text, painting, crayon, graphite, abstract, glitch, deformed, mutated, ugly, disfigured, long body, lowres, bad anatomy, bad hands, missing fingers, extra digits, fewer digits, cropped, very displeasing, worst quality, bad quality, sketch, jpeg artifacts, signature, watermark, username, simple background",
    recommended: {
      cfg_scale: 4.0,
      steps: 30,
      sampler: "Euler a",
      width: 832,
      height: 1216,
    },
  },
  {
    label: "Hassaku XL (アニメ)",
    value: "hassakuXLIllustrious_v22.safetensors",
    family: "illustrious_anime",
    description: "アニメ系・Illustrious系・Danbooruタグ推奨",
    basePrompt: "masterpiece, best quality, very aware, newest, absurdres, ultra-detailed, detailed face, detailed eyes",
    baseNegative: "worst quality, bad quality, jpeg artifacts, source_pony, source_furry, signature, watermark, monochrome, sketch, lowres, bad anatomy, bad hands, missing fingers, extra fingers",
    recommended: {
      cfg_scale: 5.0,
      steps: 28,
      sampler: "Euler a",
      width: 832,
      height: 1216,
    },
  },
];
