export const OPTIONS = {
  scene_type: [
    { label: "ソロ（1人）",     value: "solo" },
    { label: "男女カップル",    value: "couple_mf" },
    { label: "女女カップル",    value: "couple_ff" },
    { label: "複数（3人以上）", value: "group" },
  ],
  gender: [
    { label: "女性", value: "female" },
    { label: "男性", value: "male" },
  ],
  age: [
    { label: "ティーン",   value: "teen" },
    { label: "20代前半",   value: "young adult, early 20s" },
    { label: "20代後半",   value: "adult, late 20s" },
    { label: "30代",       value: "mature, 30s" },
    { label: "熟女",       value: "mature woman, milf" },
  ],
  ethnicity: [
    { label: "日本人", value: "japanese" },
    { label: "韓国人", value: "korean" },
    { label: "中国人", value: "chinese" },
    { label: "白人",   value: "caucasian" },
    { label: "ラテン系", value: "latina" },
    { label: "黒人",   value: "black" },
  ],
  skin_tone: [
    { label: "色白",   value: "fair skin, pale skin" },
    { label: "標準",   value: "normal skin tone" },
    { label: "小麦色", value: "tan skin, lightly tanned" },
    { label: "褐色",   value: "dark skin, deeply tanned" },
  ],
  body_type: [
    { label: "華奢",     value: "very slender, petite, thin body" },
    { label: "スレンダー", value: "slender, lean body" },
    { label: "スリム",   value: "slim" },
    { label: "普通",     value: "normal body" },
    { label: "グラマー", value: "curvy" },
    { label: "むっちり", value: "chubby, voluptuous" },
  ],
  breast_size: [
    { label: "小さい", value: "small breasts" },
    { label: "普通",   value: "medium breasts" },
    { label: "大きい", value: "large breasts, busty" },
    { label: "爆乳",   value: "huge breasts, very large breasts" },
  ],
  pubic_hair: [
    { label: "未指定",         value: "" },
    { label: "無毛（パイパン）", value: "bald pussy, shaved" },
    { label: "ナチュラル",     value: "pubic hair" },
    { label: "薄め",           value: "thin pubic hair" },
    { label: "濃いめ",         value: "thick pubic hair" },
    { label: "整えた",         value: "trimmed pubic hair" },
    { label: "ハート型",       value: "heart-shaped pubic hair" },
  ],
  face_type: [
    { label: "清楚",       value: "elegant beauty, refined face, pure look" },
    { label: "ギャル",     value: "gyaru style, glamorous makeup, bold look" },
    { label: "クール",     value: "cool beauty, sharp features, mature look" },
    { label: "元気",       value: "cheerful face, bright expression, lively look" },
    { label: "上品",       value: "graceful, sophisticated face, classy" },
    { label: "アンニュイ", value: "languid expression, dreamy look, melancholic beauty" },
    { label: "セクシー",   value: "sexy face, sensual look, sultry beauty" },
    { label: "童顔",       value: "baby face, youthful features, cute face" },
  ],
  hair_color: [
    { label: "黒",   value: "black hair" },
    { label: "茶",   value: "brown hair" },
    { label: "金",   value: "blonde hair" },
    { label: "白",   value: "white hair" },
    { label: "銀",   value: "silver hair" },
    { label: "赤",   value: "red hair" },
    { label: "ピンク", value: "pink hair" },
  ],
  hair_style: [
    { label: "ショート",     value: "short hair" },
    { label: "ボブ",         value: "bob hair" },
    { label: "セミロング",   value: "medium hair" },
    { label: "ロング",       value: "long hair" },
    { label: "ツインテール", value: "twin tails" },
    { label: "ポニーテール", value: "ponytail" },
    { label: "お団子",       value: "hair bun" },
    { label: "巻き髪",       value: "curly hair, wavy hair" },
  ],
  eye_color: [
    { label: "茶", value: "brown eyes" },
    { label: "黒", value: "black eyes" },
    { label: "青", value: "blue eyes" },
    { label: "緑", value: "green eyes" },
    { label: "赤", value: "red eyes" },
    { label: "紫", value: "purple eyes" },
    { label: "金", value: "golden eyes" },
  ],
  eye_shape: [
    { label: "大きい", value: "big eyes" },
    { label: "切れ長", value: "sharp eyes, slanted eyes" },
    { label: "垂れ目", value: "droopy eyes" },
    { label: "つり目", value: "tsurime, upturned eyes" },
  ],
  mouth: [
    { label: "微笑み", value: "smile mouth" },
    { label: "自然",   value: "neutral mouth" },
    { label: "開口",   value: "open mouth" },
    { label: "舌出し", value: "tongue out" },
  ],
  expression: [
    { label: "笑顔",       value: "happy expression, bright smile" },
    { label: "微笑み",     value: "soft smile, gentle smile" },
    { label: "真顔",       value: "neutral expression" },
    { label: "色っぽい",   value: "seductive expression, sultry look" },
    { label: "挑発的",     value: "provocative expression, teasing look" },
    { label: "恥ずかしげ", value: "shy expression, blushing" },
    { label: "切ない",     value: "melancholic expression, longing look" },
    { label: "驚き",       value: "surprised expression" },
    { label: "ウィンク",   value: "winking, one eye closed" },
    { label: "誘惑",       value: "seductive expression, bedroom eyes, sultry look" },
    { label: "恍惚",       value: "ecstatic expression, blissful look" },
    { label: "焦らし",     value: "teasing expression, playful smirk" },
    { label: "上目遣い",   value: "looking up at viewer, upward gaze" },
    { label: "見下し",     value: "looking down at viewer, condescending look" },
    { label: "潤んだ瞳",   value: "teary eyes, watery eyes" },
    { label: "頬染め",     value: "blushing cheeks, flushed face" },
    { label: "舌なめずり", value: "licking lips, tongue out" },
    { label: "口元に手",   value: "hand near mouth, covering mouth" },
  ],
  outfit: [
    { label: "なし",               value: "" },
    { label: "制服",               value: "school uniform" },
    { label: "セーラー服",         value: "sailor uniform" },
    { label: "ブラウス",           value: "blouse, formal shirt" },
    { label: "Tシャツ",            value: "t-shirt, casual wear" },
    { label: "ワンピース",         value: "dress, one-piece dress" },
    { label: "ニット",             value: "knit sweater" },
    { label: "オフィス",           value: "business suit, office wear" },
    { label: "ドレス",             value: "elegant dress, evening gown" },
    { label: "着物",               value: "kimono" },
    { label: "浴衣",               value: "yukata" },
    { label: "水着",               value: "swimsuit, bikini" },
    { label: "ビキニ",             value: "string bikini, micro bikini" },
    { label: "競泳水着",           value: "competitive swimsuit, one-piece swimsuit" },
    { label: "スクール水着",       value: "school swimsuit" },
    { label: "ランジェリー",       value: "lingerie, underwear" },
    { label: "セクシーランジェリー", value: "sexy lingerie, see-through lingerie" },
    { label: "ベビードール",       value: "babydoll lingerie, sheer babydoll" },
    { label: "Tバック",            value: "thong, g-string" },
    { label: "ガーターベルト",     value: "garter belt, stockings" },
    { label: "網タイツ",           value: "fishnet stockings" },
    { label: "スポーツ",           value: "sportswear, athletic wear" },
    { label: "メイド服",           value: "maid outfit" },
    { label: "ナース服",           value: "nurse uniform" },
    { label: "バニーガール",       value: "bunny girl outfit, bunny suit" },
    { label: "チャイナドレス",     value: "china dress, qipao" },
    { label: "シャツのみ",         value: "wearing only an oversized shirt, boyfriend shirt" },
    { label: "バスタオル",         value: "wrapped in bath towel, towel only" },
  ],
  outfit_color: [
    { label: "白",   value: "white" },
    { label: "黒",   value: "black" },
    { label: "赤",   value: "red" },
    { label: "青",   value: "blue" },
    { label: "ピンク", value: "pink" },
    { label: "紫",   value: "purple" },
    { label: "黄",   value: "yellow" },
    { label: "緑",   value: "green" },
    { label: "ベージュ", value: "beige" },
  ],
  outfit_material: [
    { label: "標準",     value: "" },
    { label: "レース",   value: "lace" },
    { label: "シルク",   value: "silk, satin" },
    { label: "メッシュ", value: "mesh" },
    { label: "ラテックス", value: "latex" },
    { label: "レザー",   value: "leather" },
    { label: "シースルー", value: "sheer fabric, transparent" },
    { label: "デニム",   value: "denim" },
    { label: "ニット",   value: "knit" },
  ],
  outfit_state: [
    { label: "濡れ",         value: "wet clothes, soaked" },
    { label: "はだけた",     value: "open shirt, partially undressed" },
    { label: "ずり下ろした", value: "pulled down, slipping off shoulder" },
    { label: "めくれた",     value: "lifted skirt, skirt flip" },
    { label: "破れた",       value: "torn clothes, ripped" },
    { label: "汗ばんだ",     value: "sweaty, glistening skin" },
  ],
  underwear: [
    { label: "ノーマルブラ",   value: "bra" },
    { label: "スポーツブラ",   value: "sports bra" },
    { label: "レースブラ",     value: "lace bra" },
    { label: "ブラレス",       value: "no bra" },
    { label: "ノーマルパンティ", value: "panties" },
    { label: "Tバック",        value: "thong" },
    { label: "レースパンティ", value: "lace panties" },
    { label: "紐パン",         value: "side-tie panties" },
    { label: "ノーパン",       value: "no panties" },
    { label: "ガーターベルト", value: "garter belt" },
    { label: "ストッキング",   value: "stockings, thighhighs" },
    { label: "ニーソックス",   value: "kneehighs" },
    { label: "ベビードール",   value: "babydoll, lingerie" },
    { label: "コルセット",     value: "corset" },
    { label: "Cストラップ",    value: "c-string" },
    { label: "パンツ丸見え",   value: "panty shot, panties visible" },
  ],
  exposure: [
    { label: "保守的",   value: "modest clothing, fully covered" },
    { label: "標準",     value: "" },
    { label: "やや露出", value: "slightly revealing outfit" },
    { label: "露出多め", value: "revealing outfit, exposed skin" },
    { label: "セクシー", value: "very revealing, sexy outfit" },
  ],
  shot_type: [
    { label: "全身",       value: "full body" },
    { label: "上半身",     value: "upper body" },
    { label: "顔アップ",   value: "close-up, face focus" },
    { label: "バストアップ", value: "bust shot" },
    { label: "カウボーイ", value: "cowboy shot" },
    { label: "ポートレート", value: "portrait" },
    { label: "局部アップ", value: "pussy focus" },
    { label: "胸アップ",   value: "breast focus" },
  ],
  angle: [
    { label: "正面",       value: "front" },
    { label: "横",         value: "side" },
    { label: "斜め",       value: "3/4" },
    { label: "煽り",       value: "from below" },
    { label: "俯瞰",       value: "from above" },
    { label: "真上",       value: "from directly above, top-down view" },
    { label: "真下",       value: "from directly below, worm's-eye view" },
    { label: "ローアングル", value: "low angle shot" },
    { label: "ハイアングル", value: "high angle shot" },
    { label: "POV",        value: "POV, first person view" },
    { label: "肩越し",     value: "over the shoulder" },
    { label: "自撮り風",   value: "selfie" },
    { label: "鏡越し",     value: "mirror selfie" },
    { label: "覗き見",     value: "peeking" },
    { label: "アイレベル", value: "eye level" },
  ],
  pose: [
    { label: "立ちポーズ",   value: "standing" },
    { label: "座り",         value: "sitting" },
    { label: "正座",         value: "seiza" },
    { label: "あぐら",       value: "indian style" },
    { label: "横座り",       value: "wariza" },
    { label: "仰向け",       value: "on back" },
    { label: "うつ伏せ",     value: "on stomach" },
    { label: "横向き",       value: "on side" },
    { label: "四つん這い",   value: "all fours" },
    { label: "しゃがみ",     value: "squatting" },
    { label: "ひざまずき",   value: "kneeling" },
    { label: "反り返り",     value: "arched back" },
    { label: "手を後ろ",     value: "arms behind back" },
    { label: "手を頭",       value: "arms up, hands on head" },
    { label: "胸を強調",     value: "pushing breasts together" },
    { label: "お尻突き出し", value: "presenting ass" },
    { label: "開脚",         value: "spread legs" },
    { label: "M字開脚",      value: "m legs" },
    { label: "膝立て",       value: "knees up" },
    { label: "自慰",         value: "masturbation" },
    { label: "誘惑",         value: "seductive pose" },
    { label: "恥じらい",     value: "embarrassed pose, covering" },
    { label: "見せつけ",     value: "showing off" },
  ],
  position: [
    { label: "正常位",     value: "missionary" },
    { label: "騎乗位",     value: "cowgirl position" },
    { label: "背面騎乗位", value: "reverse cowgirl" },
    { label: "後背位",     value: "doggystyle" },
    { label: "対面座位",   value: "sitting sex" },
    { label: "立位",       value: "standing sex" },
    { label: "横位",       value: "spooning" },
    { label: "寝バック",   value: "prone bone" },
    { label: "抱擁",       value: "embracing" },
    { label: "添い寝",     value: "lying together" },
    { label: "重なり",     value: "on top of another" },
    { label: "対面",       value: "face to face" },
    { label: "跨り",       value: "straddling" },
    { label: "シックスナイン", value: "69" },
    { label: "囲み",       value: "surrounded" },
    { label: "並列",       value: "side by side" },
    { label: "重なり多人数", value: "pile" },
  ],
  action: [
    { label: "キス",       value: "kissing" },
    { label: "ディープキス", value: "french kiss, tongue" },
    { label: "抱擁",       value: "hugging" },
    { label: "愛撫",       value: "caressing, fondling" },
    { label: "胸を揉む",   value: "breast grab" },
    { label: "髪を撫でる", value: "hair touching" },
    { label: "行為中",     value: "sex" },
    { label: "激しい行為", value: "rough sex" },
    { label: "ソフトな行為", value: "gentle sex" },
    { label: "フェラチオ", value: "fellatio" },
    { label: "クンニ",     value: "cunnilingus" },
    { label: "手コキ",     value: "handjob" },
    { label: "パイズリ",   value: "paizuri" },
    { label: "絶頂中",     value: "orgasm, ahegao" },
    { label: "行為後",     value: "after sex, afterglow" },
    { label: "中出し",     value: "cum inside" },
    { label: "ぶっかけ",   value: "cum on body, bukkake" },
  ],
  location: [
    { label: "寝室",   value: "bedroom" },
    { label: "バスルーム", value: "bathroom" },
    { label: "シャワー室", value: "shower" },
    { label: "リビング", value: "living room" },
    { label: "キッチン", value: "kitchen" },
    { label: "教室",   value: "classroom" },
    { label: "保健室", value: "nurse office" },
    { label: "オフィス", value: "office" },
    { label: "会議室", value: "meeting room" },
    { label: "ホテル", value: "hotel room" },
    { label: "ラブホ", value: "love hotel" },
    { label: "温泉",   value: "hot spring, onsen" },
    { label: "プール", value: "pool" },
    { label: "ビーチ", value: "beach" },
    { label: "海",     value: "ocean" },
    { label: "公園",   value: "park" },
    { label: "神社",   value: "shrine" },
    { label: "路地",   value: "alley" },
    { label: "電車内", value: "train interior" },
    { label: "車内",   value: "car interior" },
    { label: "屋上",   value: "rooftop" },
    { label: "森",     value: "forest" },
    { label: "廃墟",   value: "ruins" },
  ],
  situation: [
    { label: "通常",   value: "" },
    { label: "起床",   value: "just woke up, morning" },
    { label: "入浴中", value: "bathing" },
    { label: "入浴後", value: "wet hair, after bath" },
    { label: "着替え中", value: "changing clothes, undressing" },
    { label: "着替え後", value: "getting dressed" },
    { label: "食事中", value: "eating" },
    { label: "仕事中", value: "working" },
    { label: "休憩中", value: "resting, on break" },
    { label: "寝起き", value: "lazy morning" },
    { label: "就寝前", value: "before sleep" },
    { label: "居眠り", value: "sleeping, dozing" },
    { label: "拘束",   value: "bondage, tied up" },
    { label: "監禁",   value: "confined, captive" },
    { label: "公衆",   value: "in public" },
    { label: "屋外露出", value: "exhibitionism, outdoor" },
    { label: "痴漢",   value: "groping" },
    { label: "覗き",   value: "voyeurism" },
    { label: "隠れて", value: "hiding, secret" },
    { label: "待機",   value: "waiting" },
    { label: "誘惑中", value: "seducing" },
  ],
  mood: [
    { label: "甘い",       value: "sweet, romantic" },
    { label: "激しい",     value: "passionate, intense" },
    { label: "淫靡",       value: "lewd, erotic" },
    { label: "神聖",       value: "pure, divine" },
    { label: "背徳的",     value: "forbidden, immoral" },
    { label: "切ない",     value: "melancholic" },
    { label: "ミステリアス", value: "mysterious" },
    { label: "退廃的",     value: "decadent" },
    { label: "緊張感",     value: "tense atmosphere" },
    { label: "リラックス", value: "relaxed, calm" },
    { label: "怪しい",     value: "suspicious, eerie" },
    { label: "夜の雰囲気", value: "night atmosphere" },
  ],
  nsfw_level: [
    { label: "なし",          value: "" },
    { label: "軽（チラ見せ）", value: "cleavage, suggestive, slightly revealing" },
    { label: "中（下着）",    value: "lingerie, underwear, panties" },
    { label: "強（トップレス）", value: "topless, exposed breasts" },
    { label: "全裸",          value: "nude, naked, completely bare" },
  ],
} as const;

export type ModelFamily = "sdxl_real" | "pony_real" | "illustrious_anime";

export interface ModelDef {
  label: string;
  value: string;
  family: ModelFamily;
  description: string;
  basePrompt: string;
  baseNegative: string;
  recommended: {
    cfg_scale: number;
    steps: number;
    sampler: string;
    width: number;
    height: number;
  };
}

export const MODELS: ModelDef[] = [
  {
    label: "Nova Asian XL v7.0",
    value: "novaAsianXL_illustrious_v7.safetensors",
    family: "illustrious_anime",
    description: "アジア系リアル・Illustrious系",
    basePrompt: "masterpiece, best quality, amazing quality, very aesthetic, high resolution, ultra-detailed, absurdres, scenery, photorealistic, depth of field, photorealistic details",
    baseNegative: "anime, 3d, rendered, modern, old, oldest, cartoon, graphic, text, painting, crayon, graphite, abstract, glitch, deformed, mutated, ugly, disfigured, long body, lowres, bad anatomy, bad hands, missing fingers, extra digits, fewer digits, cropped, very displeasing, worst quality, bad quality, sketch, jpeg artifacts, signature, watermark, username, simple background",
    recommended: {
      cfg_scale: 4.0,
      steps: 30,
      sampler: "Euler a",
      width: 832,
      height: 1216,
    },
  },
  {
    label: "Hassaku XL (アニメ)",
    value: "hassakuXLIllustrious_v22.safetensors",
    family: "illustrious_anime",
    description: "アニメ系・Illustrious系・Danbooruタグ推奨",
    basePrompt: "masterpiece, best quality, very aware, newest, absurdres, ultra-detailed, detailed face, detailed eyes",
    baseNegative: "worst quality, bad quality, jpeg artifacts, source_pony, source_furry, signature, watermark, monochrome, sketch, lowres, bad anatomy, bad hands, missing fingers, extra fingers",
    recommended: {
      cfg_scale: 5.0,
      steps: 28,
      sampler: "Euler a",
      width: 832,
      height: 1216,
    },
  },
];
